package edu.jkwsql.gui;

import javax.swing.*;
import java.awt.*;

/**
 * Created by Dimitri on 4/18/14.
 * Autogenerated GUI class, used for accessing GUI elements
 */
public class InputGUI extends JFrame {
    private JTabbedPane tabbedPane;
    private JPanel mainPanel;
    private JPanel buttonPanel;
    private JButton queryButton;
    private JPanel databaseNamePanel;
    private JPanel tableNamePanel;
    private JPanel hostPanel;
    private JPanel portNumberPanel;
    private JPanel usernamePanel;
    private JPanel passwordPanel;
    private JTextField databaseNameField;
    private JTextField tableNameField;
    private JTextField hostField;
    private JTextField portNumberField;
    private JTextField usernameField;
    private JPasswordField passwordField;
    private JLabel databaseNameLabel;
    private JLabel tableNameLabel;
    private JLabel hostLabel;
    private JLabel portNumberLabel;
    private JLabel usernameLabel;
    private JLabel passwordLabel;
    private JPanel SPanel;
    private JPanel nPanel;
    private JPanel VPanel;
    private JPanel FPanel;
    private JPanel sigmaPanel;
    private JTextField SField;
    private JTextField nField;
    private JTextField VField;
    private JTextField FField;
    private JTextField sigmaField;
    private JLabel SLabel;
    private JLabel nLabel;
    private JLabel VLabel;
    private JLabel FLabel;
    private JLabel sigmaLabel;
    private JButton phiJSONButton;
    private JCheckBox executeQueryCheckBox;
    private JCheckBox generateOutputFileCheckBox;
    private JPanel phiFilePanle;
    private JPanel dbFilePanel;
    private JButton dbJSONButton;
    private JTextPane outputTextPane;

    public InputGUI() throws HeadlessException {
        setContentPane(mainPanel);

        pack();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    public JButton getQueryButton() {
        return queryButton;
    }

    //    Database connection settings
    public JTextField getDatabaseNameField() {
        return databaseNameField;
    }

    public JTextField getTableNameField() {
        return tableNameField;
    }

    public JTextField getHostField() {
        return hostField;
    }

    public JTextField getPortNumberField() {
        return portNumberField;
    }

    public JTextField getUsernameField() {
        return usernameField;
    }

    public JPasswordField getPasswordField() {
        return passwordField;
    }

    public JButton getDbJSONButton() {
        return dbJSONButton;
    }

    //    Phi operands
    public JTextField getSField() {
        return SField;
    }

    public JTextField getnField() {
        return nField;
    }

    public JTextField getVField() {
        return VField;
    }

    public JTextField getFField() {
        return FField;
    }

    public JTextField getSigmaField() {
        return sigmaField;
    }

    public JCheckBox getExecuteQueryCheckBox() {
        return executeQueryCheckBox;
    }

    public JCheckBox getGenerateOutputFileCheckBox() {
        return generateOutputFileCheckBox;
    }

    public JButton getPhiJSONButton() {
        return phiJSONButton;
    }

    public JTextPane getOutputTextPane() {
        return outputTextPane;
    }

    public JTabbedPane getTabbedPane() {
        return tabbedPane;
    }
}


